sqlectron/sqlectron-gui

.babelrc
main.js
package.json

The react-hot-loader has been deprecated. The new module is react-transform-hmr.

Replace react-hot-loader

---

src/components/header.jsx
src/containers/query-browser.jsx

Contains: Logo, current server and db and close connection button
PS: The breadcrumb still static. To implement it properly we have to decide in which store we gonna keep the selected server and database. Lets decide it after finish the connection management screen.

Create header menu

---

package.json

There's a bug when using electron version 0.37.x . If you try to connect to saved connection that is not up at the moment and connection refuses, it goes into an infinite load window instead of returning to server management with error connection message.
For example, I shut down postgresql client and tried to connect to previously saved postgresql database connection. Instead of normally handled error I got following:
As you can see CONNECTION_FAILURE action was not fired up, although it showed up in a console that connection refused. `Connection error {"code":"ECONNREFUSED"...} `
After a minute or so, whole window was blank.
Since the bug showed up after last commit, I tried to reconstruct it with several electron versions and found out its not working with electron 0.37.x . …

Downgrade electron to last version where handling db error connection works

---

src/renderer/actions/connections.js

Resolved issue #105 . Thing was that `serverSession` was still hanging on unsuccessful connection, so if you switched between different servers and previous one had an error connection, same error was returned.

Fixes #105

---

package.json
src/renderer/components/query.jsx

Thing was that ace editor triggered its resize method automatically only on window resize so it had to be invoked  manually. It's called now on ResizeableBox resize.
Seems that `onResize` method wasn't available in previous `react-resizable` version so I updated `package.json` (I also tried using Resizeable directly but I had other troubles with that). So you'll have to do `npm install` for this to work.

Fixes #109 - Query box now resizes well

---

package.json
src/renderer/actions/connections.js

Included defaultDatabase argument in [here](https://github.com/BornaP/sqlectron-gui/blob/1140a45ff46e10b35b8d2b6fcf57bd32bdad1c35/src/renderer/actions/connections.js#L58). Now everything should work smoothly with this [commit](https://github.com/sqlectron/sqlectron-core/pull/11/commits/3e8b4ebbf54d85797a4bfb60009b53866cfbb55e) in sqlectron-core.

Closes #96

---

src/renderer/components/query-result-table.jsx

Spent more time debugging this than fixing the code :smile: 
Thing was that attributes in JSON can be mixed up because it is, by definition, unordered structure. I still don't know the reason why this happened when there was more than 15 attributes in our case, but it did. So instead of depending on keys order in JSON (using `Object.keys()`), I changed it to use fields array received as a function parameter. It works now as expected!

Fixes #111

---

package.json
src/renderer/components/server-modal-form.jsx

This feature auto fill the port when choose one database...
We can not merge it yet as it depends of generate a tag for https://github.com/sqlectron/sqlectron-core/pull/12
I'll just leave it open to review code and once we generate a tag for  sqlectron-core, i can bump the https://github.com/sqlectron/sqlectron-gui/blob/master/package.json#L51 dependency

Add default port when choose database

---

package.json
src/renderer/actions/queries.js
src/renderer/components/query.jsx
src/renderer/containers/query-browser.jsx

So I took some time today to figure this out. First off, if we do not plan to use autocomplete, react-ace =< 2.8.0 should be used, because upgrading to ^3.x.x causes some [problems](https://github.com/securingsincity/react-ace/issues/95). After some debugging and fixing unpredicted behavior, here it is - simple but neat autocompletion! It completes SQL keyword and words user recently typed (that would be column and table names in most of the cases I guess).
Thou adding autocomplete was a few lines of code, there were some unexpected behavior issues. `onChange` event on AceEditor now fires more often although string remains the same, which caused infinite number of `UPDATE_QUERY` actions. That's why I had to add [this](https://github.com/BornaP/sqlectron-gui/commit/55f5894a0f261cfcf3a544a3d …

Add query autocompletion

---

app/package.json
src/renderer/actions/sqlscripts.js
src/renderer/components/database-item.jsx
src/renderer/components/database-list-item-metadata.jsx
src/renderer/components/database-list-item.jsx
src/renderer/components/database-list.jsx
src/renderer/containers/query-browser.jsx
src/renderer/reducers/index.js
src/renderer/reducers/routines.js
src/renderer/reducers/sqlscripts.js

PR resolving (partially - not yet for routines) issue #125 .
So here it is in short:
- Database objects are now moved into `database-item.jsx` component because of context menu. I found this a cleanest solution, because context menu should be a property of database object (all links in menu are related exclusively to that object).
- Context menu is built dynamically [here](https://github.com/BornaP/sqlectron-gui/blob/125-objects-sql-definitions/src/renderer/components/database-item.jsx#L35) .Reason, as explained in comment in a code, is that there's no need to built context menu for each object (table/view) before it's needed, it just slows down application, especially when loading big number of objects (test on db with 130 tables, it took 2 secs). This way is much faster and neater.
- …

#125 objects sql definitions

---

src/renderer/components/query-result-table.scss

Pull request that resolves issue #126 
Table rows now have always the same height as long texts are not broken into more lines anymore. After certain number of chars, '...' is appended instead of the rest of the text. I've put fixed `max-width ` to 220 pixels, because I found out that corresponds to the same maximum number of characters shown in table cell in MySQL Workbench (which I took as a example). That can be changed if someone has better suggestion.
How it looked before:
How it looks now:
I haven't implemented modal that @krolow suggested in the issue, because @maxcnunes proposed using [FixedDataTable](https://facebook.github.io/fixed-data-table/) where columns can be resized so user would be able to see full text that way (that's how many others SQL client's work). Also, full …

Fix table rows scaling long texts

---

src/renderer/actions/queries.js
src/renderer/actions/sqlscripts.js

Explained here: [#141 (comment)](https://github.com/sqlectron/sqlectron-gui/pull/141#issuecomment-218437013)
Instead of removing previous query with selected SQL script, script is now appended in new row to query editor.

Append query script instead of updating whole query editor

---

src/browser/app.js
src/browser/menu/darwin.js
src/browser/menu/index.js
src/browser/menu/linux.js
src/browser/menu/win32.js
src/browser/remote.js
src/browser/window.js
src/renderer/components/database-item.jsx
src/renderer/components/footer.jsx
src/renderer/components/header.jsx
src/renderer/components/update-checker.jsx

Leave deprecated API and support new one. [Electron API changes](http://electron.atom.io/blog/2015/11/17/electron-api-changes). 
This change does not affect app behavior (it works with current v0.36.12), but is necessary for upgrade to v1.x.x.
Ready for squash&merge.

Change to new way electron modules are required for easier upgrade

---

src/renderer/components/query.jsx
src/renderer/containers/query-browser.jsx

Minor fixes to get rid of console errors. 
There was unused required `PropType` in query component that caused error upon establishing connection without specified database. Second one is related to `ResizableBox` - since NaN is actually a number in JS, it solves that requirement for height property and doesn't change menu behavior :)

Minor bug fixes

---

app/package.json
src/renderer/actions/connections.js
src/renderer/components/prompt-modal.jsx
src/renderer/components/server-modal-form.jsx
src/renderer/containers/query-browser.jsx
src/renderer/reducers/connections.js

Show a prompt modal asking for the private key passphrase in case the user has checked the "Passphrase" checkbox in the server configuration.
Close #155.
Close #117 as well since have upgrade sqlectron-core which has the fixing for that bug.

Add support for private key passphrase

---

package.json

Finally, major version that works for us! :tada: 
Promises are now handled properly. There are bunch of warnings thrown in console but I guess they are related to Chrome v50.0.x, since I noticed them as of electron v1.1.0 which was bump to newer Chrome version. App works as expected anyways! :)
Since minor changes related to migrating to new API were already implemented in 131bf85154c3f976553a669f373695d58dc05049, this upgrade did not need any additional changes.

Upgrade to electron stable major, v1.1.2

---

src/renderer/components/query-result-table.jsx

The user can resize later. But it starts with only 220px.

Show result columns with max 220px

---

src/renderer/actions/connections.js

When trying to connect while using the git version of sqelectron, 
i got the weird issue of
> Cannot read property 'privateKeyWithPassphrase' of undefined
here is a quick fix for that
using git , postgresql
mandatory gif :p

 🐛 fix: fix when connecting in local and trying to reach ssh settings

---

src/renderer/components/database-diagram-modal.jsx
src/renderer/components/database-diagram.jsx
src/renderer/containers/query-browser.jsx

Added feature that enables user to automatically add related tables when (s)he right clicks on a table while making diagram.
This does not work with diagrams loaded from files at the moment.
How it works (captured just a part of the screen):
Ignore the colors, screen capturing tool messed them up a bit.

Feature: Add related tables on right click

---

package.json
src/renderer/actions/databases.js
src/renderer/components/database-diagram-modal.jsx
src/renderer/components/database-diagram.css
src/renderer/components/database-diagram.jsx
src/renderer/containers/query-browser.jsx
src/renderer/reducers/databases.js
src/renderer/reducers/tables.js
src/renderer/utils/file-handler.js

Title says it all, PR implements feature enabling user to export diagram to `.png` and `.jpeg` format. :tada:
Next to save button, there's  simple dropdown button which offers user option to export diagram to one of the formats.
Although I thought it will be much simpler to export to SVG then png/jpeg, it turned out to be quite opposite. Reason is following. When I was creating diagram I followed JointJS [doc and tutorials](http://jointjs.com/tutorial/html-elements) on offical page. There is actually tutorial and example on how to build your custom elements containing plain HTML. Now it turns out, you can not simply do `svgImage = paper.svg` ,because `svg` JointJS spits out does not contain custom HTML elements. JointJS places them just above real basic `svg` elements (which I knew before …

Export diagram to image format - .png and .jpeg

---

src/renderer/components/query-result-table.jsx
src/renderer/components/query-result-table.scss

Changes:
- Fix height when result only has one row and the way to calculate multiple row height.
- Remove scrollbar from header table
Modified files:
- src/renderer/components/query-result-table.jsx
- src/renderer/components/query-result-table.scss

Doesn't show scrollbar on header any more, fix height for one or multiples rows

---

src/renderer/components/server-modal-form.jsx

For now the connection management screen is quite clutter (for good reasons)
and things might not go by reducing the number of options available....
i propose to "hide" the ssh panel if the "ssh tunnel" switch is not active.
which cut down significantly the size of that panel
Before
After

feat: display ssh configuration only if checked to unclutter the screen

---

src/renderer/components/server-modal-form.jsx

When you opened the server modal you got an error about an input field that is null and shouldn't...
here is a fix about it, and in the meantime i fixed a linting / consistency issue by replacing this.state.ssh to previously defined ssh.

fix: Fix warning about null input and fix style

---

src/renderer/actions/connections.js

If you tried to test a connection, we tried to disconnect it using a
not existing method. here is an attempt to fix this

fix: fix closing connection for a test connection

---

src/renderer/components/override-ace.css
src/renderer/components/query.jsx

As described in #191, 
the ACE component render a kind of weird highlight..
here is an attempt to fix that using an additional css file.

fix: Style fix trying to unblurr retina render.

---

src/renderer/components/database-list-item-metadata.jsx
src/renderer/components/table-submenu.jsx

I was frustrated while browsing the database, 
stumbling upon many "No result found" after clicking the view submenu to open it.
So i thought about having some kind of visual distinction.. here is my take
Before:
After:

feat: Add visual distinction to indicate if there are items below

---

src/renderer/components/query-result-table.jsx

here is an attempt to fix the scroll misalignment 
while having more rows than could fit on the screen, 
should fix #233 ... at least from here :)

fix: substract table scroll from header to sync scrolls in results

---

src/renderer/components/header.jsx

Hi, 
Here is a litte proposition with a little PR, 
i was really intrigued  by the choice of the "disconnect" icon, as semantic ui says, it was the "Ban" icon... which is not really what we want...
i tried the "sign-out" which is what feels more natural , but the look does not right to me : 
so i tried the universally understood "power off", and seems better, 
what do you think ?
Another question i had was about the reconnect icon; aside from the icon that don't feel really obvious to me either, isn't it possible to remove it ? or maybe put it only when we are disconnected or smth ?
what do you guys think?

improve: Change disconnect icon to poweroff

---

src/renderer/containers/query-browser.jsx

@maxcnunes  refactor the tab list that work really better now, 
but i think it "clutter" the screen a bit while you don't have many tab open...
here is a propostion about hidding arrow if the tab list fit in the screen
what do you think?

ux: hide tab mover (left/right) when the tab list fit on screen

---

src/renderer/components/server-list-item.jsx

When connecting to 2 db one in local one via ssh, 
you have no ways to distinct them.
Here is an attempt at fixing that

feat: add 'via' in the server list to make distinction with ssh

---

src/renderer/containers/query-browser.jsx

I think the way to create a new tab  is a bit hidden, 
as in mysql it's "recommanded" to run queries in distinct tabs, we should make it a bit more visible.
i tried to add a button in the tab list , that's where it feels the more natural to me, 
but i'm not really sure about the design or the placement, 
what do you think ?

[question] Add new tab button

---

src/renderer/components/prompt-modal.jsx

it's really annoying to have to type the passphrase, then grab the mouse, and click "ok" instead of just pressing "enter" as usual.

feat: allow press 'enter' to submit promp modal like passphrase and all

---

src/renderer/components/server-modal-form.jsx

#253 
If you tried to create a new server and never touched user/password fields it would save fine, but if you typed something in the user/password fields and then erased it, the GUI didn't allow you to save the server anymore.

Server can be saved without a password or a user

---

src/renderer/components/database-list-item.jsx
src/renderer/components/database-list.jsx
src/renderer/containers/query-browser.jsx

As the tab is related to to the database select in the left panel, 
i thought it would be a good idea to highlight the current tab's database, to make a parallel between the two...
here is a gif explaining that.

highlight db on switching tab

---

docs/app/keyboard-shortcuts.md
src/browser/app.js
src/browser/menu/darwin.js
src/browser/menu/linux.js
src/browser/menu/win32.js

Hey everyone!  This is to resolve #278 
- Keybinding to reload window is Ctrl/Cmd-Shift-R (to mimic behavior cache ignoring keybinding in Firefox and Chrome)
- Ctrl/Cmd-R now also Executes query (keeping Ctrl/Cmd-Enter)
I may be wrong, but I don't thing multiple accelerators can be assigned in the Electron menus.  To get around this, I added an event listener for `browser-window-created` in `src/browser/app.js` that adds the duplicate shortcut to execute a query.
Any thoughts or changes needed?
Thanks!

Issue 278 - change keybinding for window reload

---

src/browser/app.js
src/browser/menu/darwin.js
src/browser/menu/linux.js
src/browser/menu/win32.js

Global shortcut should be avoided since we don't want to the shortcut work on the OS global scope.

Ovewrite reload shortcut without global settings

---

src/renderer/components/server-modal-form.jsx

When adding a new local database, the filepath can be chosen from a file dialogue instead of writing it out by hand.
In the Database/Keyspace input, the filepath of a database had to be selected manually.
Now, it can be selected via a file path dialogue.
resolves #303

Use a File Path Dialogue Window to add a local Database

---

src/browser/menu/darwin.js
src/browser/menu/linux.js
src/browser/menu/win32.js
src/renderer/actions/queries.js
src/renderer/containers/query-browser.jsx
src/renderer/reducers/queries.js

Added option for user to open `.sql ` files in current active tab.
User can open sql from file with option in window menu, under File -> Open Query (right next to Save Query option); or with shortcuts `Cmd+O` for MacOS and `Ctrl+O` for Linux/Win users.
Tab name is automatically updated with file name (extension excluded of course). 
I didn't save filename into redux state because it's used for saving as well. Maybe user does not want to save opened SQL under same filename. When we add 'Save As' option, persisting filename to redux state will make sense.

Add open query from file option (resolves #223)

---

src/renderer/containers/query-browser.jsx

Fixes bug that disabled users from resizing side menu. Probably didn't work for quite some while, since width used was fixed, while value that was changed through state haven't been used.

Fix #296 - sidemenu resizing

---

src/renderer/components/query.jsx
src/renderer/containers/query-browser.jsx

In regards to #274 
This change causes each open tab to remain in the DOM instead of being unmounted when tabs are changed. As a result, each `AceEditor` component needs a unique name, and so `query-browser` is creating one by appending the unique `queryId` to the string `querybox` and passing it as a prop.

Preventing state loss on switching tabs

---

src/renderer/components/collapse-icon.jsx
src/renderer/components/database-item.jsx
src/renderer/components/database-list-item-metadata.jsx

Referenced in #316 
I added in `database-list-item-metadata` a grouping on the key `schema` of all the elements in the list.
The way it's implemented, if the result of the group is `undefined`, the string `'undefined'` or an empty string (`''`) it should continue rendering as it currently does, that is, in a long, flat list.
I also modified `database-item` slightly as I borrowed code from there (the collapse arrow) and pulled that borrowed code out into a new component named `collapse-icon`, which renders the collapse icon based on a direction prop passed in.
`database-list-item-metadata`, when grouping by `schema` will render a list of `schemas` with dropdowns to the left. When clicking one, a list of all the items with that schema will then be rendered, with a `leftPadding` of 15px to …

Grouping database items under schema dropdowns

---

src/renderer/components/react-resizable.css

In regards to #348
Grabbed the `react-resize-handle` class and made it 100% high so it follows the entire line.
I thought I'd try a different cursor and see how you felt about it. 
To me the grab icon means "I can move this thing around the screen", not "I can resize a column" so I changed it to `col-resize` and gave it the `!important` tag to overwrite the one given by `react-resizable`

Made resize span for database list full height, changed cursor

---

src/renderer/store/configure.js

Redux logger seems to need the initial action log to be a `console.log` and not a `console.debug`.
By changing it to a `console.log` you can get the dropdowns under the actions that show the before and after of the store, as well as the value of the action.
Before (you can see 3 of the items are expanded, but nothing appears):
After:

fixed the redux logger to include sub-items under action logs

---

src/renderer/components/query.jsx

See the screenshot below.
I've added a toggle button that enables / disables wrapping in the query editor as per #298 so that it is no longer necessary to keep scrolling horizontally. 
I can gladly move this toggle elsewhere in the ui or put it a menu somewhere - I wasn't too sure about where it was supposed to be. 
Also, I did take into account the editor box resizing and tested to make ensure that didn't mess up the placement.

Added checkbox to toggle wrapping in query editor (#298)

---

src/renderer/components/query-result-table.jsx
src/renderer/components/query-result.jsx

Before this PR, re-sizing the sidebar doesn't cause QueryResult to re-render:
After this, it'll re-render when we stop dragging:
I'm experimenting with ways to re-render as we drag but changing `query-browser`'s `onResizeStop` to `onResize` was really laggy. I tried debouncing it but it just didn't fire at that point until I stopped dragging.
Open to ideas, but in the mean time this small change is better than leaving it as is IMO.

Re-rendering QueryResult when sidebar width changes

---

src/renderer/containers/query-browser.jsx

This pull request targets issue #317.
A collapse bar is put just to the left of the sidebar, making use of the space between the sidebar and the window border.

Add collapse to sidebar

---

src/renderer/components/server-modal-form.jsx

Password reveal, fixes #398
Give users an ability to show previously saved passwords.

Reveal previous saved password in the connections.

---

src/renderer/components/settings-modal-form.jsx

Fixes https://github.com/sqlectron/sqlectron-gui/issues/413
I decided to use HTML5 range control (no dependency) instead of third party Semantic UI library (lots of dependencies that needs to be imported for us to use it).
**Benefits:**
1. No need to do extra validation on the form
2. Look nicer and easier to use from users' perspective.
**Screenshot:**

Change Zoom Factor Control to slider

---

src/renderer/actions/servers.js
src/renderer/containers/server-management.jsx

Refer to this issue for more details...
https://github.com/sqlectron/sqlectron-gui/issues/409
Below is a short description
Edit and Other commands don't work for RECENTLY DUPLICATED CONNECTIONS
1. duplicate an existing connection
2. try to edit it (notice it's not working)...
Connect button works, but the edit button doesn't work.
I'll check to see if I can send in a PR.

Fix Edit Button for RECENTLY DUPLICATED / NEW CONNECTIONS

---

package.json

Let's just upgrade jquery to avoid security issue/warning :)
everything seems to still works after this.

fix: upgrade jquery to 3.3 to avoid security issues

---

package.json

Older versions of electron-builder get stuck on the "building DMG" step when building on macOD High Sierra, e.g. https://github.com/electron-userland/electron-builder/issues/2320. Later versions don't have this problem.

Upgrade electron-builder

---

.travis.yml

It looks like there's been an unintended change in a transitive dependency that is causing Travis to break due to usage of `async function`. Support for this was added in Node 7+, and so this updates things to the next LTS release after that, node 8, attempting to keep the node version from changing as much as possible for the next release.
The GH_TOKEN that is defined in the travis.yml file is no longer valid either it seems, so it was removed. A new GH_TOKEN will be defined using the Travis-CI secrets system.

Update travis build configuration

---

appveyor.yml

The currently set token is no longer valid, which causes a HTTP 401 error to be thrown when electron-builder goes to look up release information. This PR replaces it with a new, valid token.
Additionally, similar to #485, this updates the build environment to use Node 8 due to a transitive dependency using the `async function` syntax which was supported in Node 7+. Given that Node 6 EOL was years ago and is supported in Ubuntu 18.04, this should be fine.

Update appveyor build configuration

---

package.json

There's no real BC breaks that affects sqlectron-gui to worry about, and for the most part is just updating supported node versions to all modern node versions, especially getting node 12 working.

update node-sass to 4.14.0

---

package.json

Updates sqlectron-core to ^8.1.0. It's changelog:
> ## Features
>
>* Add cassandra authentication support
>* Support MySQL caching_sha2_password authentication (default for MySQL 8)
>* Use os.homedir to find user home directory (instead of hand-rolled implementation)
>* Add function to database clients to get version of currently connected client
>* Replace usage of deprecated createCipher / createDecipher with createCipheriv / createDecipheriv
>* Add official support for MySQL 8 and Postgresql 12
>* Add official support for cassandra 2.x and 3.10+
>* Add official support for MariaDB 10.1+
>* Add official support for Node 10 and 12 for sqlectron-core
>
>## Fixes
>
>* Fix querying information_schema table on MySQL 8 returning results in different casing than prior versions
>* Fix not being …

bump sqlectron-core to ^8.1.0

---

package.json

Upgrading to ^22.x requires jumping to node 10 as minimum supported runtime from node 8. The principle reason though for upgrading was just to include https://github.com/electron-userland/electron-builder/commit/8f099f5 to make it possible to move all build stuff from appveyor + travis to just GitHub actions, which should now be doable with this patch.

upgrade electron-builder to ^21.2.0

---

.github/workflows/build.yml

So that it will be possible to download the artifacts from GH to test in-progress work, without necessarily having to build it locally as well.
A future step would be to create an individualized list of files to upload and so could download a specific artifact for a given architecture / os, but that can come later in an iteration on this after electron-builder is further upgraded in a future version.

add upload artifact step to gh build

---

package.json

The electron-builder by default only functions on draft releases. However, GH actions only operates on published releases. As such, need to add this configuration to allow electron-builder to update existing publishes with release artifacts.

Update electron-builder publish type to released from draft

---

.github/workflows/build.yml
.github/workflows/publish.yml
docs/development/run-from-source.md

This bumps sqlectron to require >= 10.x to develop. This is principally to make it easier to bring in the latest versions of various dependencies which for the most part require a minimum of 10.x (e.g. like the various webpack loaders). It's been out in the wild as the LTS release for ~2 years that it's safe to assume people will minimally have this version available.

bump minimum version of node to 10.x

---

package.json

This version of react-select had an incompatible peerDependency on the version of react used by sqlectron. Upgrading does not cause any issues that did not already exist in the project (see #504).

bump version of react-select

---

.gitattributes

Marking these files as binary files in the `.gitattributes` so that they don't get potentially messed up on windows with its wacky git crlf settings.

explicitly mark binary files in gitattributes

---

package.json

Before this change, got this error when running the `dev` script on Windows:
```
E:\Github\sqlectron-gui>npm run dev
> sqlectron@1.31.0 dev E:\Github\sqlectron-gui
> concurrently --names 'webpack,electron' --prefix name 'npm run dev:webpack' 'npm run dev:electron'
['webpack] 'np' is not recognized as an internal or external command,
['webpack] operable program or batch file.
[electron'] 'run' is not recognized as an internal or external command,
[electron'] operable program or batch file.
[] The filename, directory name, or volume label syntax is incorrect.
[] 'np' is not recognized as an internal or external command,
[] operable program or batch file.
[] 'run' is not recognized as an internal or external command,
[] operable program or batch file.
[] The filename, directory name, or …
```

fix quotation style in npm run script for windows usage

---

package.json

Using the caret here has brought in changes with redshift that break the GUI. This module (and probably all dependencies) has been pinned for now to prevent that break.

Pin version of sqlectron-core

---

package.json

`sqlite3` only has pre-built binaries up to 8.2 line. There's not really anything necessary in the later versions of the 8.x line to necessitate upgrading further until ready to move to sqlite3 5.

pin version of electron

---

src/renderer/components/settings-modal-form.jsx

This fixes `margin-top` to be `marginTop`, and get rid of react warning about it.

fix react style key to be camelcase

---

src/renderer/components/settings-modal-form.jsx

This is a further continuation of the fix started in #457. The problem stems from that on first start, the zoom factor does not exist within the config.json file, and so would have `parseFloat(undefined)`, which then causes the `NaN` label.
This better guards the render to ensure the value is set to some numerical value if it's not set, so that the `NaN` will not happen, unless someone manually tampers with the file and breaks things.
The form itself has a minimum of `0.4` so we can take this simplistic `||` check and not worry about the conversion of the `0 || 1` case.

fix zoomFactor showing NaN on first start

---

src/browser/menu/darwin.js
src/browser/menu/linux.js
src/browser/menu/win32.js

It's a feature I need on my small laptop, where I often zoom in to make text more readable.
Tested on Linux (NixOS) running Electron 8.

add keyboard/menu-bar zoom controls

---

src/renderer/components/query-result-table.jsx

closes #447
This query result code has a bug where if you run a query that does not change the shape of the returned results (fields, etc.), the query results table would in-turn not re-render as the child `<Grid>` object did not use the actual row values as prop value.

fix query results not re-rendering if field information did not change

---

vendor/renderer/semantic-ui/README.md
vendor/renderer/semantic-ui/semantic.js

closes #504 
Opening / closing a select dropdown (such as in the Settings window to adjust log level) would cause the modal window to be redrawn with its `top` css element changed to now point to wherever the user was scrolled on the page. This would generally mess up trying to use the select box (especially if it was off-screen), and mess up the modal generally. This was happening because the modal window was using semantic-ui for styling, and built into it was a method to watch for mutations to the DOM tree and refresh the modals on change. However, this conflicts with the React design where components were being added/removed in the DOM tree for the select window, which was triggering the refreshes.
Semantic-UI has been adjusted so that it will no longer refresh itself on DOM changes …

fix opening select boxes changing modal top location

---

package-lock.json
package.json
src/renderer/components/react-tabs.scss
src/renderer/containers/query-browser.jsx

Relevant release notes: 
* https://github.com/reactjs/react-tabs/releases/tag/v1.0.0
* https://github.com/reactjs/react-tabs/releases/tag/v2.0.0
The main change was in how classes were now named, and how they were not given automatically. The extra specificity for `react-tabs__tab` was to make sure it took precedence over semantic.css.
Tested for #311 which was the foundation of using the fork, and it remains fixed here, with all tabs remaining usable.

upgrade to react-tabs to ^2

---

src/renderer/utils/file-handler.js

Closes #540 
This broke in the move to electron 8.2.5 where electron 6 changed the signature of this function to have a callback to instead use a promise interface. This modifies the show(Save|Open)Dialog functions to now utilize that promise, while still wrapping the result into the same form as was being used before where the `resolve` is given the singular filename (if there is one) while it rejects in cases where no file is selected (due to canceling) or we hit an error case.

fix the open/save query functionality

---

package-lock.json
package.json
src/renderer/actions/connections.js
src/renderer/containers/app.jsx
src/renderer/containers/server-management.jsx
src/renderer/entry.jsx
src/renderer/index.html
src/renderer/reducers/connections.js

Closes #537
This upgrades the react-router dependency to ^3, which brings in support for react 16 from it. I chose not to upgrade it further at this time as v4 and v5 have more extensive API changes, and as indicated in #537, upgrading react-router can happen in concert with upgrading react.

upgrade react-router to ^3

---

src/browser/menu/darwin.js
src/browser/menu/linux.js
src/browser/menu/win32.js
src/renderer/actions/queries.js
src/renderer/containers/query-browser.jsx

Added the "save as" feature to save the current query into a new file.
The shortcuts are:
Windows: Ctrl+Shift+S
Linux: Ctrl+Shift+S
Mac OS: Cmd+Shift+S
Related issue: #566

Add "save as" to save queries into a new file

---

package.json

Closes #510 
With https://github.com/electron-userland/electron-builder/issues/5285 getting closed automatically with no feedback from developer team, have to assume that `sh` builds are not a priority (or maybe even supported) for them, so better to remove them from being produced going forward, as much as some people might like to have it.

Remove sh build target for linux

---

src/renderer/components/database-list-item.jsx
src/renderer/components/database-list.jsx
src/renderer/containers/query-browser.jsx

This adds a new context menu item when right clicking on a database name to allow you to open a new tab for that database.

add open tab menu item to DB right click menu

---

src/browser/window.js

Adds context menu when running in devMode to allow you to "Inspect Element" on things to be taken to their DOM node to look at styling information. Very handy.

add right-click inspect context menu on devMode

---

src/browser/update-checker.js
src/browser/window.js
src/renderer/components/update-checker.jsx

Converts the update-checker to a functional component using hooks. Additionally, I cleaned up the integration of the box appearing to make it a bit more consistent on the dev build as that would often times take longer than 2 seconds to boot up. Now, we wait first for the update-checker component to have mounted, and then the main process checks for version and notifies back. Could also modify to kick off interval to check version string in the future.

convert update-checker to react functional component

---

package-lock.json
package.json

This upgrades react-redux to its latest version, which we can do as it places a minimum requirement of React 16.8. This will allow us to now rewrite components that utilize redux to use its new hooks.

upgrade react-redux to ^7

---

src/renderer/components/database-diagram-modal.jsx
src/renderer/components/database-filter.jsx
src/renderer/components/database-item.jsx
src/renderer/components/database-list-item-metadata.jsx
src/renderer/components/database-list-item.jsx
src/renderer/components/database-list.jsx
src/renderer/components/message.jsx
src/renderer/components/preview-modal.jsx
src/renderer/components/prompt-modal.jsx
src/renderer/components/query-result-table-cell.jsx
src/renderer/components/query-result-table.jsx
src/renderer/components/query.jsx
src/renderer/components/server-filter.jsx
src/renderer/components/server-modal-form.jsx
src/renderer/components/settings-modal-form.jsx
src/renderer/components/table-submenu.jsx
src/renderer/containers/app.jsx
src/renderer/containers/query-browser.jsx

The `context` argument to the constructor is part of the [legacy context](https://reactjs.org/docs/legacy-context.html) system that React put in place in its early days. Nowadays, there's other, better ways to do context if you need it, however, the context system is not used at all, so we can just safely remove the arg and do no migration stuff.

remove deprecated context constructor arg

---

src/browser/window.js

Closes #466
Adds a handler for `will-navigate` to prevent it from going to a URL that is not the URL of the electron window itself. Not sure how they triggered the issue within that issue, but tested that this fixes it by trying to do `window.location = 'https://example.com';` within the developer console. Without the patch, it would go to the site, with patch, it will not.

prevent outside sqlectron navigation

---

.github/workflows/build.yml
.github/workflows/publish.yml

Fix the linux build: https://github.com/sqlectron/sqlectron-gui/runs/2018631610
```
Run sudo apt-get install libgnome-keyring-dev icnsutils graphicsmagick rpm bsdtar
Reading package lists...
Building dependency tree...
Reading state information...
Package bsdtar is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
libarchive-tools
````

Fix linux build

---

.eslintrc.js
src/browser/config.ts
src/browser/core/config.ts
src/browser/core/crypto.ts
src/browser/core/limit.ts
src/browser/core/servers.ts
src/browser/core/utils.ts
src/browser/core/validators/server.ts
src/browser/menu/darwin.ts
src/browser/menu/index.ts
src/browser/menu/linux.ts
src/browser/menu/win32.ts
src/browser/update-checker.ts
src/common/types/config.ts
src/common/types/menu.ts
test/browser/test.config.ts
test/browser/test.servers.ts
test/browser/utils-stub.ts
test/browser/validators/test.server.ts
test/e2e/helper.ts

I noticed that the linter wasn't detecting many typing issues for `src/browser` code because the `@typescript-eslint/explicit-module-boundary-types` rule was turned off. 
PS: That same rule still turned off for `src/renderer` because turning it on now probably would require converting all files to typescript, or at least have a bunch of lint issues to be fixed right now. Leaving it for when/if we decide to convert those files to typescript (new files we should use typescript, but I don't mind keeping old ones in JS for now).

Fix lint issues for src/browser

---

webpack.config.js

This sets the webpack `ts-loader` config to use the `tsconfig.build.json`. This in-turn means we will omit the test directory on building / compiling, which is beneficial to development so that we're not hitting a bunch of type errors or whatever in their as working in src/.

set webpack ts-loader to use build tsconfig

---

src/renderer/components/query-result.jsx

Fixes #573
This fixes the crash where on running a query that's not recognized, but also returns an empty resultset, the app would crash. Now, we'll just print a nice generic "Query success" type message in-lieu of anything better.

do not render table with if no fields or rows

---

src/browser/config.ts
src/browser/core/config.ts
src/browser/core/utils.ts
src/common/types/config.ts
test/browser/test.config.ts
test/browser/test.servers.ts

Closes #596
When sqlectron is started for the first time with an empty config file, a number of errors are thrown, namely that:
* servers does not exist, throwing an "map on undefined" error
* log.level does not exist, throwing an "level on undefined" error
To capture the behavior here that much of the config file is optional, I've introduced a new type "ConfigFile", where then "Config" is a concrete implementation within the GUI itself after loading the file. I've also made the utils functions more generic as they could work on anything really, not just Config objects.

Fix error on starting sqlectron with no config file

---

src/renderer/components/override-select.css

When using the `react-select` inputs, the cursor was not centered within the input, rather it was at the top of the box, which just looked odd. This fixes that, so that the cursor now appears properly vertically centered.

Fix centering of cursor in react-select inputs

---

package-lock.json
package.json
src/browser/window.ts

Closes https://github.com/sqlectron/sqlectron-gui/issues/550
Now that we are not using remote anymore for sqlectron-db-core calls, and instead we are using IPC calls and running that in the browser process, which is a node process, there is no need anymore to build native dependencies to Electron anymore. It allow us to upgrade to latest version of Electron, ~which is actually required to fix https://github.com/sqlectron/sqlectron-gui/issues/471 because a new version of ssh2 that supports new auth types depends on Node12.~ ([just noticed Electron v8 is already on Node12](https://www.electronjs.org/releases/stable?version=8&page=5#release-notes-for-v800)).
I tested it running from source and a compiled version for Mac, and both worked fine with MySQL and Sqlite databases.
PS: It is …

Upgrade electron to v12

---

src/browser/core/utils.ts
test/browser/test.utils.ts

These are unused elsewhere in the app. They only existed within sqlectron-core to maintain backwards compatibility, but that's no longer necessary as it's been merged into the gui itself.

remove unused sqlectron-db-core exports

---

src/renderer/store/configure.ts

The redux devtool was not being properly loaded, rendering it useless.
Unfortunately, the devtool does have a bug where it uses APIs that are not in electron causing an error in the console (see #767), but the extension still works properly for the most part.

Fix using the redux devtool extension

---

src/browser/core/servers.ts
src/common/types/api.ts
src/common/types/server.ts
src/renderer/actions/servers.ts
test/browser/test.servers.ts

Will fix https://github.com/sqlectron/sqlectron-gui/issues/630
Because of the issue described on https://github.com/sqlectron/sqlectron-gui/issues/630, we cannot pass custom properties through the error object anymore. As far as I know, only the server validations suffer from this problem.

Fix server validation not showing errors in the UI

---

src/renderer/components/server-modal-form.jsx

As a follow-up [to this](https://github.com/sqlectron/sqlectron-gui/pull/625), from the author of [connection-string] ;)
* Safer and simpler way to access the first host details. See [Virtual Properties](https://github.com/vitaly-t/connection-string#virtual-properties).
* The initial code tried to re-implement `passwordHash` option that [connection-string] supports. It also changes the default `#` symbol to `*` instead, to keep it consistent with how original code worked.
[connection-string]:https://github.com/vitaly-t/connection-string

Improve ConnectionString usage

---

src/renderer/actions/connections.ts
src/renderer/actions/queries.ts
src/renderer/reducers/connections.ts
src/renderer/reducers/queries.ts

Will fix https://github.com/sqlectron/sqlectron-gui/issues/643 and https://github.com/sqlectron/sqlectron-gui/issues/319.
It was accessing the configuration properties directly from `action.config`, but the configuration data is actually at `action.config.data`.

Fix query configurations from file

---

package-lock.json
package.json
webpack.config.js

Will close https://github.com/sqlectron/sqlectron-gui/issues/659.
None of the updates in the package.json actually fixed the issue, but I left them anyway just to make sure they are all up to date.
What really fixed the issue was `npm i -D @babel/runtime` so it updated the package-lock.json to use the latest version of `@babel/runtime` `v7.14.0` for the NPM dedupe on other dependencies. Since we don't really use `@babel/runtime` for this project I later removed it, which isn't an issue because the configuration on package-lock.json to use the latest version was kept anyway:
```
"dependencies": {
"@babel/runtime": {
"version": "7.14.0",
"resolved": "https://registry.npmjs.org/@babel/runtime/-/runtime-7.14.0.tgz",
"integrity": "sha512-JELkvo/DlpNdJ7dlyw/eY7E0suy5i5GQH+Vlxaq1nsNJ+H7f4Vtv3jMeC …
```

Fix buggy version of babel runtime

---

package-lock.json
package.json
webpack.config.js

Will close https://github.com/sqlectron/sqlectron-gui/issues/656.
I updated connection-string to not depend on the `os` module anymore for browser consumers.
I also noticed another issue wasn't really caused by connection-string module, so I created a new ticket for that.

Remove Webpack os fallback

---

.eslintrc.js
src/renderer/components/database-item.jsx
src/renderer/components/database-list-item.jsx
src/renderer/components/query-result-table-cell.jsx
src/renderer/containers/query-browser.jsx

Will close https://github.com/sqlectron/sqlectron-gui/issues/665
I think `no-unused-vars` was turned off when we were moving to typescript and also moving to IPC handlers. There were some variables nice to keep around while not using them during that refactoring. But that refactoring is done and we can enable it back once again.

Enable no-unused-vars lint rule

---

package-lock.json
package.json

* Added support for using connection URI in server form
* Added menu item / keyboard shortcut to auto-format queries in editor
* Fixed running sqlectron with `NODE_ENV=development` set
* Fix server validation not showing errors in the UI
* Fixed color of text in server list when using dark mode

Bump version to 1.37.0

---

src/renderer/components/query.jsx

Currently if you have multiple tabs, switching to other tab does not automatically focus on the ace editor (used for query). Though  the editor itself has a caret indicator saying it's focused on. So it is kind of confusing.
I checked the code and found that there is a `autoFocus={true}` property set on the react-ace, but it's not working properly when switching tab.
Notice the caret at the end of the select statement

Fixed bug where switching tab causes loss of focus on editor

---

src/renderer/components/query.jsx
src/renderer/containers/query-browser.jsx

#687 improved things so that changing tabs would focus the editor. Unfortunately, this broke using the database filter input, but also creating a new tab would not have the editor focused.
This PR fixes it so that only changing tabs affects editor focus, as well as focusing when opening a new tab.

Improve logic for query editor focusing

---

test/e2e/test.ssh-mysql.ts

The mysql SSH e2e tests have suddenly started failing on GH actions, and I cannot fathom why that it is given that there's been no changes for that part of the code from before they started failing. The tests also work locally, making it harder to debug. 😬 
For now, this PR disables the tests, and I've created an issue (#705) to track re-enabling them in the future at some point.

Skip mysql e2e tests on CI 

---

.github/workflows/build.yml
.github/workflows/publish.yml

PR updates the version of the various `actions/*` in our GH workflows. The most important was `actions/upload-artifact` which has disabled v3 from running altogether, and so we need to upgrade it to have the workflows run at all again.
PR also disables ubuntu and macos for the moment as it previously pointed at too old a version of both where:
1. `macos-latest` does not have node 14 available
2. `ubuntu-18.04` does not have runners anymore, and using `ubuntu-22.04` fails due to `apt-get install` of dependencies that no longer exist in Ubuntu.
Luckily Windows is still works for CI, so going to rely on that for the time being as can get the others working again (which will be a requirement to make a new release).

Update github actions versions, disable ubuntu and macos
