main.js
src/actions/query.js
src/constants/action-types.js
src/containers/app.jsx
src/menu.jsx
src/pages/database.jsx
src/reducers/query.js
webpack.dev.config.js

Also was add a shortcut to execute the query by shortcut.

Configure application menu and shortcuts

---

src/actions/databases.js
src/actions/query.js
src/db/index.js
src/db/sqlectron-db.js

Moves db’s main process code to a proper file. And makes actions not aware of main process.

Organize db session

---

public/index.html
public/style.css
src/containers/app.jsx

PS:
- It is a bit slow in the GIF
- We are loading the fonts and img from the internet. In the release version they should be included in the project.

Add splash screen

---

src/browser/menu/linux.js

Onclick goes to quit in linux :)
Related to #54

Fixes quit for linux

---

webpack.dev.config.js
webpack.prod.config.js

As those old node versions does not support promise, let add babel/polyfill so at least they can get project running

Add support to node v0.10.26

---

src/renderer/containers/query-browser.jsx

Make the app feel more like 1 part instead of 2 parts.
Reduce amount of scrolling, reduce annoyance factor. :) 
p.s. Love the app!!!
Lots of scrolling
After My edits

Reduce amount of scroll bars.

---

src/renderer/components/database-list-item.jsx

I implemented [option B](https://github.com/sqlectron/sqlectron-gui/issues/114) @maxcnunes was talking about.
Idea was to reuse the same component used for database filtering. Tested it locally and it seems to work fine.
Up for comments, especially regarding styling it :)

Resolves #114 - Add db metadata filter

---

src/renderer/actions/queries.js

It's about #138 when click in cancel in save, now it's sends the action saying that there is a error...

Fix when click in cancel while saving a query

---

src/renderer/components/query.jsx

Related to #137 it's add Ctrl + "+" Ctrl + "-" to increase/decrease font-size... I'll check if I can add command to scroll as well

Add support to increase/decrease font-size

---

src/renderer/components/query.jsx
src/renderer/containers/query-browser.jsx
src/renderer/reducers/queries.js

I feel the live auto complete really annoying.
This add support to disable the live auto complete. Actually it even sets the live auto complete disabled by default. But I'm ok in changing this default value if everybody else prefers it enabled by default.

Add support to disable the live auto complete

---

src/renderer/actions/databases.js
src/renderer/components/database-list-item.jsx
src/renderer/components/database-list.jsx
src/renderer/containers/query-browser.jsx
src/renderer/reducers/columns.js
src/renderer/reducers/routines.js
src/renderer/reducers/tables.js
src/renderer/reducers/triggers.js

Add refresh database button

---

src/renderer/components/query.jsx

Ctrl/Cmd+F will show a search box inside the editor.

Configure editor search

---

src/browser/menu/darwin.js
src/browser/menu/linux.js
src/browser/menu/win32.js
src/renderer/components/database-filter.jsx
src/renderer/components/database-list-item.jsx
src/renderer/components/database-list.jsx
src/renderer/containers/query-browser.jsx

Add search shortcuts

---

package.json
src/renderer/components/query-result-table.jsx
src/renderer/components/query-result-table.scss
src/renderer/utils/convert.js

Distinguish NULL type from strings with "NULL"

---

src/renderer/components/server-modal-form.jsx

Was not including the defualt port on test connections.
Close #167.

Fix test connection

---

src/renderer/components/query-result-table.jsx
src/renderer/components/query-result-table.scss

Looking in the workbench I realized they use something like a label for NULL values. It gives a better looking.

Improve NULL cell style

---

src/renderer/components/preview-modal.jsx
src/renderer/components/query-result-table-cell.jsx
src/renderer/components/query-result-table.jsx

Pretty util for cells with large text.
It only has support to show plain text and JSON format.
But is already handful.
Close #146.

Add modal to show the cell content preview

---

README.md

Hello,
I noticed a couple of grammar issues and fixed them in this pull request

Minor grammar fixes in README.md

---

src/renderer/reducers/views.js

fix: add refresh for views when refreshing the database

---

src/renderer/components/server-modal-form.jsx

While trying the test connection i got some issues when not entering any informations
Here is a fix for that issue, not enabling the "Test" button if no client is selected.
in the meantime, i've also added a "clearable" = false on this field because it doesn't really make a sense to "clear" the client ... you can still change it of course :)
and preventing some error about uncontrolled to controlled fields

Fix connecting screen Test

---

src/renderer/components/prompt-modal.jsx
src/renderer/components/server-modal-form.jsx

it feels more natural, easy and more native
for edit/add servers modal and passphrase modal

feat: allow press 'escape' to exit modal.

---

src/renderer/actions/indexes.js
src/renderer/components/database-item.jsx
src/renderer/components/database-list-item-metadata.jsx
src/renderer/components/database-list-item.jsx
src/renderer/components/database-list.jsx
src/renderer/components/query.jsx
src/renderer/containers/query-browser.jsx
src/renderer/reducers/index.js
src/renderer/reducers/indexes.js

Add all elements necessary for indexes

Add support for listing indexes (#266)

---

src/renderer/components/server-modal-form.jsx

Make clear the Database and Schema are the initial one used in the conn

---

src/browser/config.js
src/browser/main.js

Print app version in the command line

---

docs/app/configuration-file.md

Although is possible to change this file manually. In most cases is better just use the UI since it allows to change any of this settings from there.

Simplify configuration doc

---

src/renderer/utils/convert.js

It was overwriting previous converted values

Fix CSV export

---

package.json
src/renderer/actions/connections.js
src/renderer/actions/servers.js
src/renderer/containers/server-management.jsx
src/renderer/reducers/servers.js

Fix encrypt decrypt #369

---

README.md

added what I think is a better pronunciation guide

Improve pronunciation

---

src/browser/config.js
src/browser/preload.js
src/renderer/actions/connections.js

A simple fix - thanks for the opportunity!

fixed typo in preload.js

---

src/renderer/containers/app.jsx

Prevent drag and drop causing redirect

---

src/renderer/components/settings-modal-form.jsx
src/renderer/containers/app.jsx
vendor/renderer/semantic-ui/semantic.css

Suggestion for quick dark theme option.
Refactor for css and/or body element maybe is more suitable as a core change.

Dark theme for body element (#384)

---

src/renderer/containers/app.css
vendor/renderer/semantic-ui/semantic.css

This is a further improvement for this dark teme...
https://github.com/sqlectron/sqlectron-gui/pull/401
Enable Dark Theme in the settings.
Below are sample screenshots:
**Splash Screen**
**Server Explorer**
**Settings**
**New Connection**
**Edit Existing Connection**
**Delete connection**
**Query Browser**

Dark Theme  Improvements

---

src/renderer/actions/queries.js
src/renderer/components/query-result-table.jsx
src/renderer/components/query-result.jsx
src/renderer/components/query.jsx
src/renderer/components/settings-modal-form.jsx
src/renderer/containers/query-browser.jsx

Add a checkbox for switching between comma and tab delimited CSV copy/save operations.
Add input box for custom character delimited copy/save operations.

Add Option for Custom CSV Characters - #301

---

src/renderer/components/settings-modal-form.jsx

This fixes issue #445 
This handles cases where the value is a string representation of the number

fix NaN on zoomFactor label #445

---

package.json

The usage of axios is very simple (just basically doing a simple GET request) and so this repository is not affected by any of the breaking changes that have happened.

update axios to ^0.19.2

---

README.md

After talking to @maxcnunes, I'll be taking over maintenance / development for sqlectron, with a new release coming later on this week or so, after I finish updating a handful more dependencies.

remove unmaintained notice from readme

---

README.md

Updates the demo to include some of the newer features. There's still a lot of features, and might be better to include screenshots or docs on it, rather than in a demo gif.

Update demo gif in README

---

package.json
src/browser/window.js
src/renderer/components/database-item.jsx
src/renderer/components/database-list-item.jsx
src/renderer/components/query-result-table-cell.jsx

This upgrades the version of electron used to ^8 release. Luckily, the number of things necessary to jump versions appears to be quite small. There a couple of warnings that would be good to iron out, but do not seem to cause issues in actually using sqlectron.
Closes #482

upgrade electron to 8

---

src/renderer/actions/connections.js

closes #502 
When connecting to a database, if there is no database name specified, it will attempt to use a specified default database name. However, when testing the connection, it would not also use that name, instead then falling back to however the underlying driver works. For postgres, this meant that connecting would use a default name of `postgres` and testing would use the OS user's name.
This PR makes it so that testing a connection will also use that specified default name, making behavior between the two consistent.

use default database if none specified for testing connections

---

package-lock.json
package.json

Changelog: https://github.com/sqlectron/sqlectron-gui/compare/v1.31.0...master

v1.32.0 release

---

package-lock.json
package.json
src/renderer/store/configure.js

Slight change in how importing the logger, but otherwise no big meaningful change of things.

upgrade redux-logger to ^3

---

src/browser/menu/darwin.js
src/browser/menu/linux.js
src/browser/menu/win32.js
src/renderer/components/settings-modal-form.jsx
src/renderer/containers/app.jsx
src/renderer/utils/config.js

Closes #545
Using the keyboard shortcuts for altering the zoom setting will now appropriately update the `zoomFactor` config setting.

fix zoom-in/out menu item not updating config

---

.github/workflows/publish.yml

Signed-off-by: Matthew Peveler <matt.peveler@gmail.com>

Add apt-get update to publish action

---

src/renderer/actions/queries.js
src/renderer/reducers/queries.js

don't prompt for filename if file is not new #564

---

docs/development/test-core-changes.md
package-lock.json
package.json
scripts/dev-auto-restart.js
scripts/link-sqlectron-core.sh
scripts/link-sqlectron-db-core.sh
src/browser/config.ts
src/browser/core/config.ts
src/browser/core/crypto.ts
src/browser/core/index.ts
src/browser/core/limit.ts
src/browser/core/servers.ts
src/browser/core/utils.ts
src/browser/core/validators/server.ts
src/browser/logger.ts
src/browser/main.ts
src/browser/remote.ts
test/browser/test.config.ts
test/browser/test.index.ts
test/browser/test.servers.ts
test/browser/test.utils.ts
test/browser/utils-stub.ts
test/browser/validators/test.server.ts
test/fixtures/browser/sqlectron.json
test/fixtures/browser/sqlectron.prepared.json
test/fixtures/browser/tmp.sqlectron.json

Just copied over the files from sqlectron-core into src/browser/core and changed the files extension to `.ts`. Beside a few cases, the linter didn't complain about the missing types. I am gonna create a next PR to improve the linter and properly change those files to TS standard.

Merge core module

---

package-lock.json
package.json
src/browser/app.ts
webpack.config.js

Will close #617.
Follow all security recommendations from https://www.electronjs.org/docs/tutorial/security:

Add Content Security Policy

---

package-lock.json
package.json
scripts/link-sqlectron-db-core.sh
src/browser/core/db.ts
src/browser/core/index.ts
src/browser/core/limit.ts
src/browser/core/utils.ts
src/common/types/api.ts
src/common/types/database.ts

Will fix https://github.com/sqlectron/sqlectron-gui/issues/603.
Depends on https://github.com/sqlectron/sqlectron-db-core/pull/32 to be released first.

Fix local development with linked core-db

---

.eslintrc.js
.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
src/renderer/components/checkbox.tsx
stories/components/checkbox.stories.tsx
tsconfig.json

Closes #626 
I ended up putting the `stories` directory with the storybook stuff at the top-level, to mimic the `src` and `test` split. However, given that this only includes stuff from `renderer` right now, I did not put in that folder level, and it's just assumed that `stories` -> `src/renderer`.

add storybook to the project

---

package-lock.json
package.json

There were no breaking changes for us.

Upgrade react-tabs

---

.github/workflows/build.yml
.github/workflows/publish.yml

1. update actions/checkout to v3
2. update actions/setup-node to v3
3. update actions/upload-artifact to v3

Update CI github actions versions
